#!/data/data/com.termux/files/usr/bin/bash

## Author : Trilok Singh Maitry
## Email  : triloksinghmaitry@gmail.com

#colors
R='\033[1;31m'
B='\033[1;34m'
C='\033[0;36m'
G='\033[1;32m'
W='\033[1;37m'
Y='\033[1;33m'

DIR="$(pwd)"

echo
echo -e $B"   ┌────────────────────────────────────┐"
echo -e $B"   │$R╺┳╸┏━╸┏━┓┏┳┓╻ ╻╻ ╻   $G┏━┓╺┳╸╻ ╻╻  ┏━╸$B│"
echo -e $B"   │$R ┃ ┣╸ ┣┳┛┃┃┃┃ ┃┏╋┛$Y╺━╸$G┗━┓ ┃ ┗┳┛┃  ┣╸ $B│"
echo -e $B"   │$R ╹ ┗━╸╹┗╸╹ ╹┗━┛╹ ╹   $G┗━┛ ╹  ╹ ┗━╸┗━╸$B│"
echo -e $B"   └────────────────────────────────────┘"
echo -e $B"   [$R*$B] By-$Y TSMAITRY $R//$Y TSM"
echo

echo -e $G"   [*] Installing termuxstyle..."
echo
echo -e $R"   [*] Initializing program..."
echo
echo -e $Y"   [*] Setting Up The Program..."
echo

if [ ! -d $HOME/.termux ]; then
mkdir $HOME/.termux
fi

mv $DIR/data.tar.gz $PREFIX/share
cd $PREFIX/share
echo -e $Y"   [*] Extracting Files..."$C
echo
tar -xhf data.tar.gz
chmod +x termuxstyle/theme
ln -s $PREFIX/share/termuxstyle/theme $PREFIX/bin/termuxstyle
rm $PREFIX/share/data.tar.gz
termux-reload-settings
echo -e $G"   [*] TermuxStyle Installed."
echo
echo -e $R"   [*] Program Initialized."
echo
echo -e $Y"   [*] Setup Completed."
echo
echo -e $Y"   [*] Now You Can Run This Program By Just typing $G'termuxstyle'."
echo
echo -e $G"   [*] Developed By$R TRILOK SINGH MAITRY."
echo

